- hosts: localhost
  tasks:
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/nvm.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/ghostty.yml
    - include_tasks: tasks/aerospace.yml
    - include_tasks: tasks/pnpm.yml
    - include_tasks: tasks/bun.yml
    - include_tasks: tasks/mise.yml
    - include_tasks: tasks/claude-code.yml
    - include_tasks: tasks/cursor.yml
    - include_tasks: tasks/utils.yml
